---
driver:
  name: vagrant
  network:
  - ["private_network", { ip: "192.168.33.14" }]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[fen-varnish::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
